name: Build with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Maven
      uses: actions/setup-maven@v2
      with:
        maven-version: '3.8.4'  # Specify the Maven version you want to install

#    - name: Build with Maven
 #     run: mvn clean install
